apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: r2ayne4bn-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:018e1bfea5ecab1406d10c1bb5513cf1c1e6ad74@sha256:36e3e90d25ef1b6d25e7dbb889084cc856f2d220a8f56007c1cf27f73163daf0
          name: container-image
